version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "devhabib"
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
      nx:
        patterns:
          - "@nx/*"
          - "nx"
      dev-tooling:
        patterns:
          - "eslint*"
          - "prettier*"
          - "typescript*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "devhabib"
